[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["hussainsultan <hussainz@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
xgboost = "^2.1.1"
pandas = "^2.2.3"
ipython = "^8.28.0"
scikit-learn = "^1.5.2"
attrs = "^24.2.0"

[tool.poetry.scripts]
generate-examples = "app.generate_examples:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 88
fix = true
