[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["hussainsultan <hussainz@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
xgboost = "^2.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
